language: cpp

compiler: 
  - gcc
  - clang  

before_install:
  - sudo apt-get update -d

install:
  - sudo apt-get install build-essential pkg-config cmake libgtest-dev doxygen

script:
  - bash .travis.sh

env:
  global:
  - GH_REF: github.com/jlblancoc/nanoflann.git
  - secure: "IuygPfNU6C6YhVizB1CBd6wwElKIc31IpsMOwsSVG/k/FBUH+god6OByIZqD2ALmus39hkxle0vIAu7iBdb+umYNYCxgktW4hqcDIORUuvOuPuve6dkZf7BFCn3J4oN2tMJBbI5syFh5vxuD0HtZkvZDIna6vUIFYhuUYH9u/Ag="
  matrix:
  - TASK="build"
  - TASK="test"
  - TASK="docs"

